// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrwD3-2TwOyNBUQvtgvbYUQsCBIsfK2Ts',
    appId: '1:688257271856:web:2670c3d8aef69b02a505f5',
    messagingSenderId: '688257271856',
    projectId: 'mentalhealthapp-a86e3',
    authDomain: 'mentalhealthapp-a86e3.firebaseapp.com',
    storageBucket: 'mentalhealthapp-a86e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5zSt50cDqRG4TIpoBM27MTNLueBawL1U',
    appId: '1:688257271856:android:6c0b22199d0359ada505f5',
    messagingSenderId: '688257271856',
    projectId: 'mentalhealthapp-a86e3',
    storageBucket: 'mentalhealthapp-a86e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Zz3vGgcTJx8-yMk00jW97EKLjeLuCyM',
    appId: '1:688257271856:ios:1d6f4b0e992e6264a505f5',
    messagingSenderId: '688257271856',
    projectId: 'mentalhealthapp-a86e3',
    storageBucket: 'mentalhealthapp-a86e3.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Zz3vGgcTJx8-yMk00jW97EKLjeLuCyM',
    appId: '1:688257271856:ios:1d6f4b0e992e6264a505f5',
    messagingSenderId: '688257271856',
    projectId: 'mentalhealthapp-a86e3',
    storageBucket: 'mentalhealthapp-a86e3.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrwD3-2TwOyNBUQvtgvbYUQsCBIsfK2Ts',
    appId: '1:688257271856:web:b394cbd1d9e870c4a505f5',
    messagingSenderId: '688257271856',
    projectId: 'mentalhealthapp-a86e3',
    authDomain: 'mentalhealthapp-a86e3.firebaseapp.com',
    storageBucket: 'mentalhealthapp-a86e3.firebasestorage.app',
  );
}
